name: 🌍 Refresh Google Photos (v4 Global)

on:
  schedule:
    - cron: "0 3 * * *"   # 03:00 UTC – Europe
    - cron: "0 6 * * *"   # 06:00 UTC – Asia
    - cron: "0 9 * * *"   # 09:00 UTC – Africa
    - cron: "0 12 * * *"  # 12:00 UTC – North America
    - cron: "0 15 * * *"  # 15:00 UTC – South America
    - cron: "0 18 * * *"  # 18:00 UTC – Oceania / fallback
  workflow_dispatch:       # Gör att du kan köra manuellt i Actions-fliken

jobs:
  refresh-photos:
    runs-on: ubuntu-latest
    env:
      BASE_URL: "https://gbxxoeplkzbhsvagnfsr.supabase.co/functions/v1/refresh-photos"
      AUTH: "Bearer ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}"

    steps:
      - name: 🚀 Europe batch
        run: |
          echo "Running Europe batch..."
          curl -s -X POST "$BASE_URL?region=europe&limit=1200" \
            -H "Authorization: $AUTH" -H "Content-Type: application/json" || true

      - name: 🌏 Asia batch
        run: |
          echo "Running Asia batch..."
          curl -s -X POST "$BASE_URL?region=asia&limit=1200" \
            -H "Authorization: $AUTH" -H "Content-Type: application/json" || true

      - name: 🌍 Africa batch
        run: |
          echo "Running Africa batch..."
          curl -s -X POST "$BASE_URL?region=africa&limit=1200" \
            -H "Authorization: $AUTH" -H "Content-Type: application/json" || true

      - name: 🇺🇸 North America batch
        run: |
          echo "Running North America batch..."
          curl -s -X POST "$BASE_URL?region=united%20states&limit=1200" \
            -H "Authorization: $AUTH" -H "Content-Type: application/json" || true

      - name: 🇧🇷 South America batch
        run: |
          echo "Running South America batch..."
          curl -s -X POST "$BASE_URL?region=south%20america&limit=1200" \
            -H "Authorization: $AUTH" -H "Content-Type: application/json" || true

      - name: 🇦🇺 Oceania batch
        run: |
          echo "Running Oceania batch..."
          curl -s -X POST "$BASE_URL?region=australia&limit=1200" \
            -H "Authorization: $AUTH" -H "Content-Type: application/json" || true

      - name: ✅ Summary
        run: echo "All regions processed."
