name: Refresh Photos Nightly

on:
  schedule:
    - cron: "0 3 * * *"  # kör varje dag kl 03:00 svensk tid (01:00 UTC)
  workflow_dispatch:     # gör att du även kan köra manuellt

jobs:
  run-refresh:
    runs-on: ubuntu-latest

    steps:
      - name: Invoke Supabase Edge Function
        run: |
          curl -X POST \
            "${{ secrets.SUPABASE_URL }}/functions/v1/refresh-photos" \
            -H "Authorization: Bearer ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}" \
            -H "Content-Type: application/json" \
            -d '{}'
